library(KoNLP)
library(tm)
library(stringr)
library(data.table)
library(readxl)
library(dplyr)
library(xlsx)

test = subject

#통신비
test <- gsub('수수료', '812 통신비', test$키워드)
test <- data.frame(test)

#상품
test <- gsub('\\<가지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<가슴살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<갈매기살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<갈비\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<감말랭이\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<감자\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<감초\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<강력분\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<강도다리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<거래계\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<건어물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<건포류\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<견과류\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<계란\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<계육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고기류\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고등어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고사리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고추씨\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<고춧가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<곡류외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<곡물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<곤약\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<골뱅이\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<곱창\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<공병\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<곶감\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<과일\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<과자\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<광어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<교육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<교재\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<국수나무\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<근위\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<김가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<김밥김\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<김치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<김칫속\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<깍두기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<깨소금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<깻잎\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<꽁치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<꽃게\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<꽃돔\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<꽃소금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<나물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<낙지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<날치알\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<냉면무채\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<녹두\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<논이랑산이랑\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<농사물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<농산물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<농산품외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<농수산\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<눈다랑어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<단무지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<당근\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<대게\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<대창\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<대파\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<더초이스\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<도미\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<도서대금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돈두\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돈부산물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돈뼈\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돈안심\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돈앞다리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<돌김\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<동태\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<동화책판매대금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<두부\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<둥굴레\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<뒷다리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<들깨\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<등심\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<딸기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<땅콩가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<떡볶기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<라임\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<레몬\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<마감\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<마늘\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<막창\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<맛기름\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<망고\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<매출액\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<먹태\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<메로가마살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<면세\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<멸치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<명란\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<명태\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<목살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<목전지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<무말랭이\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<무순\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<무쌈\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<무우\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<묵은지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<문어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<물류대금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<물품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<미나리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<미역\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<민물고기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<밀가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<바나나\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<바지락\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<배\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<배추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<백미\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<버섯\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<복권\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<봉지무\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<부식\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<부채살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<부산물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<블루베리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<빵가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<삼겹살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<삼치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<상추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<상품대금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<새송이\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<새우\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<샐러리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생강\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생굴\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생두\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생리대\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생선\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<생크림\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<선어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<소고기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<소금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<소맥\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<소스\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<쇠고기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<쇼핑용봉투\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<수산물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<수수\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<수입육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<숙주\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<숭어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<스티커북\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<시유\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식료품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식용란\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식자재\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식잡외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식재료\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<식품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<신고배\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<신선육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<쌀\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<씨푸드외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<아몬드\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<알탕\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<야채\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<양고기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<양곡\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<양념\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<양상추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<양파\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<어패류\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<얼음\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<연어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<연유\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<염통\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<영화관람\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오뎅\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오돌뼈\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오렌지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오이\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오죽잎\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오징어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<오겹살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<옥수수가루\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<우거지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<우목심\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<우유\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<유기농어린잎\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<유제품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<육계\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<육류대금\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<육수용\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<육제품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<은행\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<일회용품\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<자몽\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<잡육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<장어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<장족외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<적상추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<적채\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<전족\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<절각육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<절단육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<젓갈\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<정육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<조기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<족발\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<종량제봉투\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<지육\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<쪽파\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<쭈꾸미\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<참깨\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<참다랑어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<참두릅\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<참외\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<참치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<채소\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<천일염\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<천혜향\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<청경채\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<청과\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<청양고추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<축산물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<치즈\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<치커리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<치킨무\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<케이크\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<코다리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<콩나물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<키위\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<킹크랩\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<택배\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<토마토\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<토시살\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<통깨\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<통발\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<파래\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<파슬리\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<파인애플\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<파프리카\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<팜플렛\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<팥\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<포도\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<풋고추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<피망\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<한라봉\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<한우\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<한치\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<해물\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<해바라기씨\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<호두\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<호박\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<혼합곡\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<홍합\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<홍메기\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<활어\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<황태\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<후지\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<후추\\>', '146 상품', test$test)
test <- data.frame(test)
test <- gsub('\\<흑미\\>', '146 상품', test$test)
test <- data.frame(test)

#지급수수료
test <- gsub('\\<VBC시스템\\>', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('검사비', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('관리비', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('리스료', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('마감', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('바퀴벌래', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('\\<바퀴벌레\\>', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('방제', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('\\<배달대행료\\>', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('보험료', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('소독', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('시설이용료', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('온라인사용료', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('음식물수거비', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('인건비', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('인셉터', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('절단비', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('폐기물수거료', '827 지급수수료', test$test)
test <- data.frame(test)
test <- gsub('필증스티커', '827 지급수수료', test$test)
test <- data.frame(test)

#건물관리비
test <- gsub('관리비', '831 건물관리비', test$test)
test <- data.frame(test)
test <- gsub('\\<계산서\\>', '831 건물관리비', test$test)
test <- data.frame(test)
test <- gsub('\\<비과세\\>', '831 건물관리비', test$test)
test <- data.frame(test)

#수도광열비
test <- gsub('수도료', '813 수도광열비', test$test)
test <- data.frame(test)

#전력비
test <- gsub('전력기금', '814 전력비', test$test)
test <- data.frame(test)

#제품
test <- gsub('\\<밀크마스터\\>', '150 제품', test$test)
test <- data.frame(test)
test <- gsub('\\<부추\\>', '150 제품', test$test)
test <- data.frame(test)

#도서인쇄비
test <- gsub('\\<구독료\\>', '824 도서인쇄비', test$test)
test <- data.frame(test)

#소모품비
test <- gsub('\\<화환\\>', '826 소모품비', test$test)
test <- data.frame(test)
test <- gsub('\\<돼지고기\\>', '826 소모품비', test$test)
test <- data.frame(test)

#복리후생비
test <- gsub('\\<사과\\>', '809 복리후생비', test$test)
test <- data.frame(test)

#미정리계정
test <- gsub('기타', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<홍메기\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<후라이드\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<흑돼지\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<아이비피토시\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<고급제면용\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<아구\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<북채\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<제품대\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<몬스터매스제품\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<파채\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<국수용기대\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<고무장갑\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<오감\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<토지계약금\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<돈채\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<패류\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<중력외\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<수거비\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<메추리알\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<전복\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<항정살\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<무생채\\>', '250 미정리계정', test$test)
test <- data.frame(test)
test <- gsub('\\<제육\\>', '250 미정리계정', test$test)
test <- data.frame(test)



set <- cbind(main_sub$유형, main_sub$사업자번호, main_sub$사업자등록번호, main_sub$품명, subject$키워드, main_sub$계정과목, 
             test)
write.xlsx(set, file='C:/Users/fight/OneDrive/Documents/menu/set.xlsx', 
           row.names=FALSE)
